apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nova-app-cluster
  region: us-east-1
  version: "1.28"

managedNodeGroups:
  - name: nova-app-nodegroup
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    ssh:
      allow: false